### ISSUE TITLE
Base de datos oficial

### ISSUE THREAD

**Issue by nicolasugrinovic** [mauforonda/covid19-bolivia#3]
Hola, gracias por tu trabajo con todo esto. 
He visto que haces scrapping the los datos. No existe alguna base de datos oficial abierta al publico del ministerio de salud de Bolivia?

**Comment by mauforonda** [comment]
Hola, 

lo más parecido es [este repositorio](https://datos.gob.bo/dataset/casos-covid-19-acumulado-por-municipios) que describe casos acumulados por municipio entre las semanas epidemiológicas 20 (16 de Mayo) y 29 (18 de Julio). Lo subieron hace una semana y no he visto aún un anuncio al respecto. Si quieres datos por municipio de semanas previas, tengo [este otro repositorio](https://github.com/mauforonda/casos-municipios/). No hay más datos oficiales y abiertos a nivel nacional. El único municipio que publica datos abiertos es La Paz en [este sitio](https://github.com/mauforonda/casos-municipios/). Aparte de esto, sólo puedes encontrar visualizaciones y reportes en sitios del gobierno ([boliviasegura.gob.bo](https://www.boliviasegura.gob.bo/estadisticas.php), [servicio de vigilancia epidemiológica](snis.minsalud.gob.bo/)) y especialmente sus redes sociales.

**Comment by nicolasugrinovic** [comment]
@mauforonda gracias por la respuesta. Me parece curioso que estos datos no esten abiertos al publico para ser consultados y solo sea asi para las visualizaciones. Es importante que estos datos sean abiertos. Alguna idea de como solicitar acceso a ellos?

**Comment by mauforonda** [comment]
Si bien el acceso a la información es reconocido como derecho en la Constitución y normas como el decreto 28168, no está bien reglamentado, no suele cumplirse y no tienes opciones para obligar a que se cumpla. Podrías mandar una carta al Ministerio de Salud, pero lo que quieres es un recurso que se actualice regularmente. Para eso necesitas más compromiso político y probablemente una vista pública sobre la infraestructura que usan para monitorear casos. Es algo que hemos pedido muchos desde marzo sin éxito. En este tiempo, los únicos reportes regulares han sido las infografías que se comparten en redes sociales y las buenas intenciones, lideradas por agetic, no se han materializado en nada. 

El servicio web que consume este repositorio sirve para alimentar de datos a la aplicación móvil de boliviasegura. No existe nada parecido a un SLA que proteja a quienes usamos estos datos, ningún compromiso que los datos sean correctos, que el formato no cambie o que el servicio sea descontinuado. De hecho a fines de abril, el servicio fue descontinuado por un día y dejaron de actualizarse permanentemente datos para casos descartados y sospechosos. En resumen, la existencia de este servicio es un beneficio colateral de un pequeño proyecto de agetic y la existencia de este repositorio es producto de mi obsesión oportuna por mantener un archivo desde el primer día de operación de este servicio.

**Comment by nicolasugrinovic** [comment]
Es una pena esto que me cuentas. Gracias por tu trabajo y esfuerzo con todo esto.
